apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-dep
  name: my-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-dep
    spec:
      containers:
      - image: sammarcesi/tp-sysops:pr-6
        name: tp-sysops
        ports:
          - containerPort: 1234
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: my-dep
spec:
  selector:
    app: my-dep
  ports:
    - port: 1234
      targetPort: 1234
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: my-dep
spec:
  type: LoadBalancer
  ports:
  - port: 1234
  selector:
    app: my-dep
