name: CI

# Le workflow s'exécute lors d'un push sur la branche main ou sur les pull requests
on:
  push:
    branches:
      - main
  pull_request:


# On utilise des variables d'environnement pour éviter de dupliquer les mêmes valeurs dans le fichier
env:
  NODE_VERSION: 16.19.1

jobs:
  # A COMPLETER : https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
  push-docker-image:
    needs: run-e2e-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: sammarcesi/tp-sysops

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
